name: DellEMC OpenManage Ansble Continuous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [ collections ]
  pull_request:
    branches: [ collections ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build collection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible-version: [2.10.3]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install ansible (${{ matrix.ansible-version }})
        run: pip install ansible=="${{ matrix.ansible-version }}"

      - name: Build a collection tarball
        run: ansible-galaxy collection build --output-path "${GITHUB_WORKSPACE}/.cache/collection-tarballs"

      - name: Store migrated collection artifacts
        uses: actions/upload-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

  unit:
    name: Unit Tests
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.9]
        ansible-version: [2.10.3]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible (${{ matrix.ansible-version }})
        run: pip install ansible=="${{ matrix.ansible-version }}"

      - name: Download migrated collection artifacts
        uses: actions/download-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

      - name: Setup Unit test Pre-requisites
        run: |
          ansible-galaxy collection install .cache/collection-tarballs/*.tar.gz
          git clone https://github.com/ansible/ansible.git
          cp -rf ansible/test/units/compat /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/unit/
          cp -rf ansible/test/units/modules/utils.py /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/unit/plugins/modules/
          sed -i 's/units/ansible_collections.dellemc.openmanage.tests.unit/' /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/unit/plugins/modules/utils.py
          pip install wheel pytest pytest-xdist pytest-mock pytest-cov mock coverage==4.5.4 omsdk pytest-ansible==2.0.1

      - name: Run Unit tests using ansible-test
        continue-on-error: true
        run: ansible-test units --python ${{ matrix.python-version }} --coverage
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage

      - name: Generate coverage report.
        run: ansible-test coverage xml -v --group-by command --group-by version
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage

      - name: Push coverage report to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -s 'tests/output/reports/' -F units
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage

  sanity:
    name: Sanity Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        ansible-version: [2.10.3]

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install ansible (${{ matrix.ansible-version }})
        run: pip install ansible=="${{ matrix.ansible-version }}"

      - name: Download migrated collection artifacts
        uses: actions/download-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

      - name: Setup Unit test Pre-requisites
        run: ansible-galaxy collection install .cache/collection-tarballs/*.tar.gz

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --truncate 0 --coverage
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage
